### ISSUE TITLE
Server execution error 

### ISSUE THREAD

**Issue by ijobson** [velkoborsky/scaffvis#2]
Hi,

I have just started my PhD and am doing a project that involves generating scaffolds for use in deep learning, so have been trying to use your code. Unfortunately I've been having some issues, which I think are largely due to having different versions of JChem and the required libraries. I've also noticed several errors associated with chirality when importing the PubChem files. 

When I load the server, there is the error 'Error calculating scaffolds from molecule' and also 'Execution exception[[RuntimeException: java.lang.NoClassDefFoundError: com/chemaxon/marvin/editor/model/properties/NonVisiblePropertyKey]]'

Do you have any ideas about how to solve these errors, or do you have a copy of the version of JChem Suite 16.1.4.0 and its associated libraries that you used to develop this code, that could help me overcome these problems?

I am running Ubuntu 20.04; Java JDK 8; JChem 20.19.0

All the best,
Izzy

![Screenshot from 2020-11-17 14-33-23](https://user-images.githubusercontent.com/70946171/99403044-f1896c80-28e1-11eb-9632-aebbf0d61f8e.png)
![Screenshot from 2020-11-17 14-33-42](https://user-images.githubusercontent.com/70946171/99403047-f2220300-28e1-11eb-9f98-7bab9896bcd3.png)

**Comment by velkoborsky** [comment]
Hello Izzy and thank you for reporting the issue.

Would you be able to try with an older version available on the Chemaxon site? There seems to be one:

https://chemaxon.com/download?dl=%2Fdata%2Fdownload%2Finstant-jchem%2F16.1.4.0%2Finstantjchem-16.1.4.0.zip

If you would be interested in re-using larger parts of this project and update it to work with the latest (hopefully it is not that much to do), I am happy to help with that.

**Comment by ijobson** [comment]
Hi, thanks for getting back to me - I had been looking for that file for a while but couldn't find it anywhere! I've re-tried the server installation, but I'm still having a couple of problems with the GenerateHierarchy step, which is raising some issues:

`> last generator/compile:run
[debug] javaOptions: List(-Djna.nosys=true, -server, -Xmx8G, -XX:+UseConcMarkSweepGC)
[info] Running scaffvis.Application GenerateHierarchy
[info] Executing task: GenerateHierarchy.
[info] Opening MapDB file /home/chris/IzzyMiniProject/scaffvis/hierarchy/processingHierarchy.mapdb
[info] Opening MapDB file /home/chris/IzzyMiniProject/scaffvis/hierarchy/scaffoldHierarchy.mapdb
[info] Assigning unique IDs to all scaffolds...
[info] Done for level 0.
[info] Done for level 1.
[info] Done for level 2.
[info] Done for level 3.
[info] Done for level 4.
[info] Done for level 5.
[info] Done for level 6.
java.lang.RuntimeException: Nonzero exit code returned from runner: 137
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2077)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2077)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:2077)
	at sbt.Defaults$.toError(Defaults.scala:39)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$38$$anonfun$apply$39.apply(Defaults.scala:750)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$38$$anonfun$apply$39.apply(Defaults.scala:748)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (generator/compile:run) Nonzero exit code returned from runner: 137`
Do you know if there is an easy way to resolve this?

I've also had some errors when running importPubChem and GenerateScaffolds  - do I need to be concerned about these?:
importPubChem error (for *some* molecules): `[error] Nov 17, 2020 3:46:45 PM chemaxon.marvin.io.formats.smiles.SmilesImport tetrahedralParitySmi2Mol
[error] WARNING: The connectivity conditions are not fulfilled for the specified chiral center at atom 31 in the following SMILES/SMARTS: COC1=CC=C(C=C1)C2=C(C=C(C=C2)OC)N3CCC(CC3)COC4=CC(=CC=C4)[Si@@](CC(=O)O)C5CC5
[error] The chirality is ignored.`


GenerateScaffolds error for native PubChem compounds: `Finished processing Pubchem compounds. Total time: 783491 ms. Errors: 7.` 

Thanks,
Izzy
